# Generated by Django 5.1.7 on 2026-08-04 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nfc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("checkout_pending", "Checkout Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("esp_disconnected", "ESP Disconnected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("current_quantity", models.PositiveIntegerField(default=0)),
                (
                    "current_total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("esp_last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("checkout_locked", models.BooleanField(default=False)),
                (
                    "nfc_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shopping_sessions",
                        to="nfc.nfctag",
                    ),
                ),
            ],
            options={
                "db_table": "shopping_sessions",
                "ordering": ["-started_at"],
            },
        ),
    ]
